# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0006_auto_20171230_1917'),
    ]
    
    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image_url',
        ),
    ]
