# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-25 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together=set([]),
        ),
    ]
