# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-31 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20191030_2254'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postview',
            unique_together=set([]),
        ),
    ]
