# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-05 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20180611_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default=b'none'),
        ),
    ]
