# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_postarchive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postarchive',
            name='category',
        ),
    ]
