# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20190207_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(default=b'none', max_length=300),
        ),
    ]
