# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20171227_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postarchive',
            options={'ordering': ['-year']},
        ),
    ]
