# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-02 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='galleryImage',
            field=models.NullBooleanField(default=False),
        ),
    ]
