# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-02 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20190202_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='galleryImage',
            new_name='show_gallery',
        ),
    ]
