# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-24 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, default='No caption', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=gallery.models.upload_location_postimage, width_field='width_field')),
            ],
        ),
    ]
