# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('post', '0003_remove_post_num_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('posts', models.PositiveIntegerField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.Category')),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
    ]
