# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('category', '0001_initial'),
        ('post', '0007_auto_20171229_1446'),
    ]
    
    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='category.Category'),
        ),
    ]
