# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='España', max_length=20),
            preserve_default=False,
        ),
    ]
