# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='introduction',
            field=models.TextField(default='Empty'),
            preserve_default=False,
        ),
    ]
