# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 21:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [migrations.CreateModel(name='Author',
        fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('email', models.EmailField(max_length=254)),
            ('location', models.CharField(max_length=30)), ('birth_date', models.DateField(blank=True, null=True)), ('height_field', models.IntegerField(default=0)),
            ('width_field', models.IntegerField(default=0)),
            ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=posts.models.upload_location_author, width_field='width_field')),
            ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)), ], ), migrations.CreateModel(name='Category',
        fields=[('id', models.CharField(max_length=5, primary_key=True, serialize=False)), ('sort', models.IntegerField()), ('category', models.CharField(max_length=20)),
            ('css_class', models.CharField(max_length=20)), ('timestamp', models.DateTimeField(auto_now_add=True)), ('updated', models.DateTimeField(auto_now=True)), ],
        options={'ordering': ['sort'], }, ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)), ('updated', models.DateTimeField(auto_now=True)), ('num_comments', models.PositiveIntegerField()),
                ('height_field', models.IntegerField(default=0)), ('width_field', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=posts.models.upload_location_post, width_field='width_field')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.Author')),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ), migrations.CreateModel(name='PostCategory',
            fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Category')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')), ], options={'ordering': ['-post', 'category'], }, ),
        migrations.CreateModel(name='PostComment',
            fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('num_comment', models.PositiveIntegerField()), ('comment', models.TextField()),
                ('num_likes', models.PositiveIntegerField()), ('timestamp', models.DateTimeField(auto_now_add=True)), ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')), ], options={'ordering': ['post', '-num_comment'], }, ),
        migrations.AlterUniqueTogether(name='postcomment', unique_together=set([('post', 'num_comment')]), ),
        migrations.AlterUniqueTogether(name='postcategory', unique_together=set([('post', 'category')]), ),
    ]
