# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-24 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='author',
            new_name='profile',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='anonymous_email',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='anonymous_name',
        ),
    ]
