# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='No one', max_length=20),
            preserve_default=False,
        ),
    ]
