# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-24 08:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20171224_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='profile',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
