# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('posts', '0002_simplepost'), ]

    operations = [migrations.AlterField(model_name='simplepost', name='title', field=models.CharField(max_length=120), ), ]
