# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.URLField(default='#'),
            preserve_default=False,
        ),
    ]
