# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('posts', '0003_auto_20171219_2035'), ]

    operations = [migrations.AlterField(model_name='simplepost', name='image', field=models.FileField(blank=True, null=True, upload_to=''), ), ]
