# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('posts', '0003_auto_20171214_2326'), ]

    operations = [migrations.AlterField(model_name='postcomment', name='author', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Author'), ), ]
