# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('posts', '0004_auto_20171214_2330'), ]

    operations = [migrations.RemoveField(model_name='post', name='num_comments', ), ]
