# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):
    dependencies = [('posts', '0004_auto_20171219_2039'), ]

    operations = [migrations.DeleteModel(name='SimplePost', ), migrations.AlterField(model_name='post', name='image',
        field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=posts.models.upload_location_post, width_field='width_field'), ), ]
