# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('posts', '0005_remove_post_num_comments'), ]

    operations = [migrations.AddField(model_name='post', name='num_likes', field=models.PositiveIntegerField(default=0), preserve_default=False, ), ]
