# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 06:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ('posts', '0005_auto_20171219_2051'), ]

    operations = [migrations.CreateModel(name='SocialProfile',
        fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('gender',
                                                                                                                    models.CharField(blank=True,
                                                                                                                                     choices=[('male',
                                                                                                                                               'Male'),
                                                                                                                                              (
                                                                                                                                              'female',
                                                                                                                                              'Female'),
                                                                                                                                              (
                                                                                                                                              'other',
                                                                                                                                              'Other'),
                                                                                                                                              ('',
                                                                                                                                               '')],
                                                                                                                                     max_length=10,
                                                                                                                                     verbose_name='Gender')),
            ('url', models.URLField(blank=True, help_text='Where can we find out more about you?', max_length=500, verbose_name='Homepage')),
            ('image_url', models.URLField(blank=True, max_length=500, verbose_name='Avatar Picture')),
            ('description', models.TextField(blank=True, help_text='Tell us about yourself!', verbose_name='Description')),
            ('manually_edited', models.BooleanField(default=False)), ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                                                                   related_name='social_profile',
                                                                                                   to=settings.AUTH_USER_MODEL,
                                                                                                   verbose_name='Social Profile')), ],
        options={'verbose_name': 'Social Profile', 'ordering': ['user__username'], 'verbose_name_plural': 'Social Profiles', }, ), ]
