# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):
    dependencies = [('posts', '0005_auto_20171123_2248'), ]

    operations = [migrations.CreateModel(name='Category',
        fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('category', models.CharField(max_length=20)),
            ('css_class', models.CharField(max_length=20)), ('timestamp', models.DateTimeField(auto_now_add=True)), ('updated', models.DateTimeField(auto_now=True)),
            ('thumbnail', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=posts.models.upload_location, width_field='width_field')), ], ),
        migrations.AlterField(model_name='post', name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=posts.models.upload_location, width_field='width_field'), ), ]
