# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('posts', '0006_auto_20171212_2207'), ]

    operations = [migrations.AddField(model_name='post', name='category', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.Category'), ), ]
