# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('posts', '0007_post_category'), ]

    operations = [migrations.AlterField(model_name='category', name='id', field=models.CharField(max_length=5, primary_key=True, serialize=False), ), ]
