# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('posts', '0007_auto_20171222_1732'), ]

    operations = [migrations.RemoveField(model_name='socialprofile', name='user', ), migrations.DeleteModel(name='SocialProfile', ), ]
