# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('posts', '0007_remove_postcomment_num_likes'), ]

    operations = [migrations.AddField(model_name='author', name='description', field=models.CharField(default='Escritor y poeta', max_length=100), preserve_default=False, ), ]
