# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('posts', '0008_auto_20171212_2243'), ]

    operations = [migrations.AlterModelOptions(name='category', options={'ordering': ['sort']}, ),
        migrations.AddField(model_name='category', name='sort', field=models.IntegerField(default=1, max_length=1), preserve_default=False, ), ]
