# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):
    dependencies = [('posts', '0008_author_description'), ]

    operations = [migrations.CreateModel(name='PostImage',
        fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('timestamp', models.DateTimeField(auto_now_add=True)),
            ('updated', models.DateTimeField(auto_now=True)), ('height_field', models.IntegerField(default=0)), ('width_field', models.IntegerField(default=0)),
            ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=posts.models.upload_location_post, width_field='width_field')),
            ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')), ], ), ]
