# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('posts', '0009_auto_20171213_0644'), ]

    operations = [migrations.RemoveField(model_name='post', name='category', ),
        migrations.AddField(model_name='category', name='posts', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.Post'), ),
        migrations.AlterField(model_name='category', name='sort', field=models.IntegerField(), ), ]
