# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('posts', '0009_postimage'), ]

    operations = [migrations.RemoveField(model_name='postimage', name='updated', ), ]
