# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):
    dependencies = [('posts', '0010_remove_postimage_updated'), ]

    operations = [migrations.AlterField(model_name='postimage', name='image',
        field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=posts.models.upload_location_postimage, width_field='width_field'), ), ]
