# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('posts', '0010_auto_20171213_0713'), ]

    operations = [migrations.RemoveField(model_name='category', name='posts', ),
        migrations.AddField(model_name='post', name='category', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.Category'), ), ]
