# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('posts', '0011_auto_20171213_0716'), ]

    operations = [migrations.CreateModel(name='PostCategory',
        fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('timestamp', models.DateTimeField(auto_now_add=True)),
            ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Category')), ], ), migrations.RemoveField(model_name='post', name='category', ),
        migrations.AddField(model_name='postcategory', name='post', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post'), ), ]
