# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('posts', '0011_auto_20171216_1341'), ]

    operations = [migrations.AddField(model_name='postimage', name='caption', field=models.CharField(blank=True, default='No caption', max_length=50), ), ]
