# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('posts', '0012_auto_20171213_2304'), ]

    operations = [migrations.AlterField(model_name='postcategory', name='category', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Category', unique=True), ),
        migrations.AlterField(model_name='postcategory', name='post', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post', unique=True), ), ]
