# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('posts', '0012_postimage_caption'), ]

    operations = [migrations.AddField(model_name='postcomment', name='annonymous_email', field=models.EmailField(blank=True, default='none@none.com', max_length=40), ),
        migrations.AddField(model_name='postcomment', name='annonymous_name', field=models.CharField(blank=True, default='', max_length=30), ), ]
