# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('posts', '0013_auto_20171213_2306'), ]

    operations = [migrations.AlterField(model_name='postcategory', name='category', field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.Category'), ),
        migrations.AlterField(model_name='postcategory', name='post', field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.Post'), ), ]
