# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('posts', '0014_auto_20171216_1508'), ]

    operations = [migrations.AlterField(model_name='postcomment', name='author', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Author'), ), ]
