# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('posts', '0015_auto_20171216_1516'), ]

    operations = [migrations.AlterField(model_name='postcomment', name='anonymous_email', field=models.EmailField(blank=True, default='none@none.com', max_length=40, null=True), ),
        migrations.AlterField(model_name='postcomment', name='anonymous_name', field=models.CharField(blank=True, default='', max_length=30, null=True), ), ]
