# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 05:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('posts', '0016_auto_20171213_2308'), ]

    operations = [migrations.AlterModelOptions(name='postcategory', options={'ordering': ['-post', 'category']}, ), migrations.RemoveField(model_name='post', name='caption', ),
        migrations.RemoveField(model_name='post', name='height_field', ), migrations.RemoveField(model_name='post', name='width_field', ), ]
