# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('posts', '0017_auto_20171214_0658'), ]

    operations = [migrations.AddField(model_name='post', name='num_comments', field=models.PositiveIntegerField(default=0), preserve_default=False, ), ]
