# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('posts', '0018_post_num_comments'), ]

    operations = [migrations.RemoveField(model_name='post', name='num_comments', ), migrations.AddField(model_name='post', name='caption', field=models.URLField(default=''), preserve_default=False, ),
        migrations.AddField(model_name='post', name='height_field', field=models.IntegerField(default=0), ),
        migrations.AddField(model_name='post', name='width_field', field=models.IntegerField(default=0), ), ]
