# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('posts', '0019_auto_20171214_0707'), ]

    operations = [migrations.RemoveField(model_name='post', name='caption', ), ]
