# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('posts', '0020_remove_post_caption'), ]

    operations = [migrations.CreateModel(name='Comment',
        fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('user', models.CharField(max_length=20)), ('content', models.TextField()),
            ('timestamp', models.DateTimeField(auto_now_add=True)), ('updated', models.DateTimeField(auto_now=True)), ('num_likes', models.PositiveIntegerField()), ], ),
        migrations.CreateModel(name='PostComments', fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('order', models.PositiveIntegerField()),
            ('timestamp', models.DateTimeField(auto_now_add=True)), ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Comment')), ],
            options={'ordering': ['-order'], }, ), migrations.AddField(model_name='post', name='num_comments', field=models.PositiveIntegerField(default=0), preserve_default=False, ),
        migrations.AddField(model_name='postcomments', name='post', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post'), ),
        migrations.AlterUniqueTogether(name='postcomments', unique_together=set([('post', 'comment')]), ), ]
