# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('posts', '0021_auto_20171214_0713'), ]

    operations = [migrations.RenameModel(old_name='PostComments', new_name='PostComment', ), ]
