# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('posts', '0022_auto_20171214_0719'), ]

    operations = [migrations.AlterModelOptions(name='postcomment', options={'ordering': ['post', '-num_comment']}, ),
        migrations.RenameField(model_name='postcomment', old_name='order', new_name='num_comment', ),
        migrations.AddField(model_name='postcomment', name='num_likes', field=models.PositiveIntegerField(default=0), preserve_default=False, ),
        migrations.AddField(model_name='postcomment', name='updated', field=models.DateTimeField(auto_now=True), ),
        migrations.AddField(model_name='postcomment', name='user', field=models.CharField(default='Isma', max_length=20), preserve_default=False, ),
        migrations.AlterField(model_name='postcomment', name='comment', field=models.TextField(), ),
        migrations.AlterUniqueTogether(name='postcomment', unique_together=set([('post', 'num_comment')]), ), migrations.DeleteModel(name='Comment', ), ]
